[colors.primary]
background = "#0d1117"
foreground = "#c9d1d9"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"

[window]
opacity = 0.95

[keyboard]
bindings = [{ key = "Return", mods = "Alt", action = "SpawnNewInstance"}]
